backend:
  name: git-gateway
  branch: main

# repo location for images
media_folder: 'src/images'

# how to import images into content
public_folder: 'src/images'

collections:
  - name: 'pages'
    label: 'Pages'
    create: false
    delete: false
    files:
      - name: about
        label: About
        file: src/pages/about.md
        format: frontmatter
        preview_path: about
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Heading', name: 'heading', widget: 'string', required: false}
          - {label: 'Body', name: 'body', widget: 'markdown'}
  - name: 'posts'
    label: 'Posts'
    folder: 'src/content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    extension: md
    format: frontmatter
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
    fields:
      - {label: 'Title', name: 'title', widget: 'string', required: false}
      - {label: 'Draft', name: 'draft', widget: 'boolean', required: false}
      - {label: 'Created', name: 'created', widget: 'datetime', date_format: 'YYYY-MM-DD', default: '', required: false}
      - {label: 'Updated', name: 'updated', widget: 'datetime', date_format: 'YYYY-MM-DD', default: '', required: false}
      - {label: 'Image', name: 'image', widget: 'image', required: false}
      - {label: 'Tags', name: 'tags', widget: 'list', required: false}
      - {label: 'Body', name: 'body', widget: 'markdown'}
